library(shiny)
library(ggplot2)
library(scales)
library(dplyr)
library(xts)
library(zoo)  # for rollapply

ui <- fluidPage(
  titlePanel("Pairs Trading Strategy Explorer"),
  
  sidebarLayout(
    sidebarPanel(
      selectInput("pair", "Choose a cointegrated pair:",
                  choices = names(zscore_signals)),
      br(),
      
      h4("Performance Metrics"),
      verbatimTextOutput("metrics"),
      
      br(),
      helpText("Performance metrics provide key statistics about the trading strategy for the selected pair. These include profitability, risk, and consistency measures, helping you evaluate strategy quality.")
    ),
    
    mainPanel(
      tabsetPanel(
        tabPanel("How It Works",
                 fluidRow(
                   column(12,
                          h3("Introduction to Pairs Trading"),
                          p("Pairs trading is a market-neutral strategy that involves trading two related assets whose prices tend to move together over time. The goal is to profit from temporary divergences in their relative prices."),
                          
                          h4("Cointegration and Price Ratio"),
                          p("We identify pairs of stocks that are cointegrated, meaning their price ratio tends to stay stable over the long term. Instead of focusing on the absolute prices, we analyze the ratio of one stock's price to the other's."),
                          p("This price ratio helps us detect when one stock is 'cheap' or 'expensive' relative to its pair."),
                          
                          h4("Z-Score: Measuring Deviation"),
                          p("The z-score measures how far the current price ratio deviates from its recent average (mean), scaled by the recent volatility (standard deviation)."),
                          p("A high positive z-score means the ratio is unusually high (potentially overpriced); a low negative z-score means the ratio is unusually low (potentially underpriced)."),
                          
                          h4("Trading Signals: Entry and Exit Points"),
                          p("We use predefined thresholds to decide when to enter or exit trades:"),
                          tags$ul(
                            tags$li(strong("Entry (z-score > +2):"), " Short the spread by selling the overpriced stock and buying the underpriced one."),
                            tags$li(strong("Entry (z-score < -2):"), " Long the spread by buying the underpriced stock and selling the overpriced one."),
                            tags$li(strong("Exit (z-score close to 0):"), " Close the position expecting the ratio to revert to its mean.")
                          ),
                          
                          h4("Parameters: Why 40 Days & Thresholds?"),
                          p("We calculate the rolling mean and standard deviation of the price ratio over the last 40 days to capture recent behavior."),
                          p("Thresholds ±2 standard deviations correspond to rare events (about 5% probability), which often present trading opportunities due to mean reversion."),
                          
                          h4("Risks and Assumptions"),
                          p("This strategy assumes the relationship between the two stocks remains stable (cointegrated). However, market dynamics can change, breaking this assumption."),
                          p("The model does not consider transaction costs, slippage, or extreme market events."),
                          p("Regular monitoring and parameter tuning are important to keep the strategy effective.")
                   )
                 )
        ),
        
        tabPanel("Z-score Plot",
                 p("This chart shows the standardized price ratio between the two stocks in the selected pair."),
                 p("The black line is the z-score, representing how many standard deviations the price ratio is from its recent average."),
                 p("The dashed red and green horizontal lines mark the entry thresholds at +2 and -2 standard deviations."),
                 p("When the z-score crosses above +2, the strategy signals a 'SHORT' position (red downward triangles). When below -2, it signals a 'LONG' position (green upward triangles)."),
                 p("The goal is to capitalize on the expectation that the price ratio will revert to its mean (blue line at 0)."),
                 plotOutput("zPlot")
        ),
        
        tabPanel("Cumulative P&L",
                 p("This chart shows the cumulative profit or loss generated by the pairs trading strategy over time for the selected pair."),
                 p("A rising line indicates profitable trades, while a declining line suggests losses."),
                 p("Use this plot to assess the overall performance and risk of the strategy."),
                 plotOutput("profitPlot")
        )
      )
    )
  )
)

server <- function(input, output) {
  
  output$zPlot <- renderPlot({
    req(input$pair)
    
    symbols <- strsplit(input$pair, "-")[[1]]
    s1 <- symbols[1]
    s2 <- symbols[2]
    
    price1 <- prices_xts[, s1]
    price2 <- prices_xts[, s2]
    ratio <- na.omit(price1 / price2)
    
    roll_mean <- rollapply(ratio, 40, mean, align = "right", fill = NA)
    roll_sd <- rollapply(ratio, 40, sd, align = "right", fill = NA)
    zscore <- (ratio - roll_mean) / roll_sd
    zscore <- na.omit(zscore)
    
    signal <- zscore_signals[[input$pair]]
    signal <- signal[index(zscore)]
    
    df <- data.frame(
      Date = index(zscore),
      Zscore = as.numeric(zscore),
      Mean = 0,  # mean in z-score space is always 0
      Upper = 2,
      Lower = -2,
      Signal = as.numeric(signal)
    )
    
    df$Trade <- ifelse(df$Signal == 1, "LONG",
                       ifelse(df$Signal == -1, "SHORT", NA))
    
    ggplot(df, aes(x = Date)) +
      geom_line(aes(y = Zscore), color = "black") +
      geom_hline(yintercept = 0, linetype = "solid", color = "blue", alpha = 0.7) +
      geom_hline(yintercept = 2, linetype = "dashed", color = "red", alpha = 0.7) +
      geom_hline(yintercept = -2, linetype = "dashed", color = "green", alpha = 0.7) +
      geom_point(data = subset(df, Trade == "LONG"), aes(y = Zscore), color = "green", shape = 24, fill = "green", size = 3) +
      geom_point(data = subset(df, Trade == "SHORT"), aes(y = Zscore), color = "red", shape = 25, fill = "red", size = 3) +
      labs(
        title = paste("Z-score and Trading Signals for:", input$pair),
        y = "Z-score",
        x = "Date",
        caption = paste(
          "Green triangles: Entry to LONG the spread (buy undervalued stock).\n",
          "Red inverted triangles: Entry to SHORT the spread (sell overvalued stock).\n",
          "Dashed lines at ±2 mark entry thresholds; blue line at 0 is mean."
        )
      ) +
      scale_x_date(date_labels = "%b %Y") +
      theme_minimal()
  })
  
  output$profitPlot <- renderPlot({
    req(input$pair)
    
    df_profit <- pair_profits[[input$pair]]
    ggplot(df_profit, aes(x = Date, y = CumulativeProfit)) +
      geom_line(color = "blue") +
      ggtitle(paste("Cumulative Profit for Pair:", input$pair)) +
      ylab("Cumulative Profit") +
      xlab("Date") +
      scale_x_date(date_labels = "%b %Y") +
      theme_minimal()
  })
  
  output$metrics <- renderPrint({
    req(input$pair)
    perf <- performance_metrics %>%
      filter(Pair == input$pair)
    
    # Nicely format metrics
    cat("Pair:", input$pair, "\n")
    cat("Total Trades:", perf$TotalTrades, "\n")
    cat("Win Rate:", scales::percent(perf$WinRate), "\n")
    cat("Average Return per Trade:", scales::dollar(perf$AvgReturn), "\n")
    cat("Sharpe Ratio:", round(perf$SharpeRatio, 2), "\n")
    cat("Max Drawdown:", scales::percent(perf$MaxDrawdown), "\n")
  })
}

shinyApp(ui = ui, server = server)
